### ISSUE TITLE
Proj4 isn't autoloaded

### ISSUE THREAD

**Issue by volkanunsal** [rgeo/rgeo#167]
I found an interesting behavior. When rgeo is loaded, Proj4 seems to be disabled. When I load the proj4 implementation manually, it seems to be enabled. I don't understand why this happens.

```
[1] pry(main)> RGeo::CoordSys::Proj4.supported?
=> false
[2] pry(main)> require "rgeo/coord_sys/proj4_c_impl"
=> true
[3] pry(main)> RGeo::CoordSys::Proj4.supported?
=> true
```

**Comment by ansonhoyt** [comment]
I'm was trying to figure this out too, so I'll share my notes. Are you on macOS?

Check the readme under [Installation](https://github.com/rgeo/rgeo#installation), which lists where rgeo looks for the Proj4 library and how to specify a different place. It needs to know during gem installation.

I installed proj4 with Homebrew, so it is in `/usr/local/bin`. This isn't one of the paths. So, I set `--with-proj-dir`. Since my application uses bundler, I did something like this to fix my rgeo build:

```
$ bundle config build.rgeo --with-proj-dir=$(dirname $(which proj))
$ gem uninstall rgeo
$ bundle install --verbose
...
Fetching rgeo 0.6.0
Installing rgeo 0.6.0 with native extensions
Building native extensions with: '--with-proj-dir=/usr/local/bin'
```
If you're using bundler, `bundle config` lets you configure [build options](http://bundler.io/man/bundle-config.1.html#BUILD-OPTIONS).
Now Proj4 is showing as supported:

````
$ rails c
> RGeo::CoordSys::Proj4.supported?
=> true
```

So far, so good. Hope that helps.

**Comment by ansonhoyt** [comment]
I spoke too soon. I'm still having Proj4 issues:

```
> RGeo::CoordSys::Proj4.supported?
=> true
> RGeo::Geographic.projected_factory
ArgumentError: Unable to determine the Proj4 for the projected coordinate system.
from /Users/ahoyt/.rvm/gems/ruby-2.4.1@my-app/gems/rgeo-0.6.0/lib/rgeo/geographic/interface.rb:404:in `projected_factory'
```

So my help may only go so far 😞

**Comment by teeparham** [comment]
Proj4 has been extracted to a separate gem, `rgeo-proj4`. Please re-open this issue in https://github.com/rgeo/rgeo-proj4 if it is still a problem. Thanks.
