### ISSUE TITLE
RGeo Fails to Read SRID from PostGIS

### ISSUE THREAD

**Issue by mzagaja** [rgeo/rgeo#170]
For any arbitrary record with a geometry column:
```
Model.last.geometry.srid
=> 0
```

Despite going into Postgres and seeing something like: `SRID=26986;POINT(245985.964199997)`

```
2.3.3 :021 > School.last.geometry.class
  School Load (0.6ms)  SELECT  "schools".* FROM "schools" ORDER BY "schools"."id" DESC LIMIT $1  [["LIMIT", 1]]
 => RGeo::Geos::CAPIPointImpl
2.3.3 :022 > School.last.geometry
  School Load (0.6ms)  SELECT  "schools".* FROM "schools" ORDER BY "schools"."id" DESC LIMIT $1  [["LIMIT", 1]]
 => #<RGeo::Geos::CAPIPointImpl:0x3ff29275e6fc "POINT (276499.6977514899 834860.7436856688)">
2.3.3 :023 > School.last.geometry.srid
  School Load (0.6ms)  SELECT  "schools".* FROM "schools" ORDER BY "schools"."id" DESC LIMIT $1  [["LIMIT", 1]]
 => 0
```

**Comment by fergyfresh** [comment]
When you are setting up your `activerecord-postgis-adapter` are you setting the SRID properly?

```
class Location < ActiveRecord::Base
  set_rgeo_factory_for_column(:latlon,
    RGeo::Geographic.spherical_factory(:srid => 4326))
end
```
I randomly saw this and thought it could help, [Snippet from this link](http://daniel-azuma.com/articles/georails/part-3).

**Comment by keithdoggett** [comment]
The `SpatialFactoryStore` in `rgeo-activerecord` should handle this and set some factories by default. If this is still an issue, feel free to reopen.

**Comment by ksouthworth** [comment]
> For any arbitrary record with a geometry column:
> 
> ```
> Model.last.geometry.srid
> => 0
> ```
> 
> Despite going into Postgres and seeing something like: `SRID=26986;POINT(245985.964199997)`
> 
> ```
> 2.3.3 :021 > School.last.geometry.class
>   School Load (0.6ms)  SELECT  "schools".* FROM "schools" ORDER BY "schools"."id" DESC LIMIT $1  [["LIMIT", 1]]
>  => RGeo::Geos::CAPIPointImpl
> 2.3.3 :022 > School.last.geometry
>   School Load (0.6ms)  SELECT  "schools".* FROM "schools" ORDER BY "schools"."id" DESC LIMIT $1  [["LIMIT", 1]]
>  => #<RGeo::Geos::CAPIPointImpl:0x3ff29275e6fc "POINT (276499.6977514899 834860.7436856688)">
> 2.3.3 :023 > School.last.geometry.srid
>   School Load (0.6ms)  SELECT  "schools".* FROM "schools" ORDER BY "schools"."id" DESC LIMIT $1  [["LIMIT", 1]]
>  => 0
> ```

I'm also experiencing this with `rgeo (3.0.0)` and `rgeo-activerecord (7.0.1)`.

I have saved the SRID inside my `geometry` column in PostgreSQL (PostGIS):
`SRID=4326;MULTIPOLYGON(((-85.1525800001104 42.06953299983154, ...`

but when I load my ActiveRecord model and call `model_record.geometry.srid` it returns `0`.

To be fair my db table does NOT have an SRID defined on it (psql query for `SELECT f_table_name AS name, srid FROM geometry_columns;`) returns an `srid` on my table of `0`, but I would think that `rgeo` or `rgeo-activerecord` would read the actual SRID that is stored in the db column value and use that if it's been stored (SRID `4326` in my specific example)?

This might be by design, but it was a bit unexpected behavior when I can see the SRID stored in the db column for this record.

**Comment by keithdoggett** [comment]
@ksouthworth yes the adapter uses a global set of factories that are set for each column based on parameters defined in the configuration. You can read more about the spatial factory store here https://github.com/rgeo/rgeo-activerecord#spatial-factories-for-columns. It is not intended to handle multiple SRIDs in the same column since most `#srid` implementations on geometries usually just check their factory's SRID.

For a use case like this, you could treat the column as string data and read WKB or WKT directly from the database and use the `WKTParser` or `WKBParser` implementations to handle multiple SRIDs and then wrap the result in a geometry. It will be more work in your models to handle this, but it should be possible with the ActiveRecord public API.

https://github.com/rgeo/rgeo/blob/c70baceb7abd4803f137c73e295005c2bfd23740/test/wkrep/wkt_parser_test.rb#L165-L172
