### ISSUE TITLE
Compatibility problem RGeo on Geos 3.8.0

### ISSUE THREAD

**Issue by D0ud0v** [rgeo/rgeo#214]
Hi,

A new version of the libgeos package was released on Linux Alpine (edge) on november 24 and since then, our docker alpine container fails to link Rgeo and Geos features.

Here's gem install verbose log :

`Building native extensions. This could take a while...
current directory: /usr/local/bundle/gems/rgeo-2.1.1/ext/geos_c_impl
["/usr/local/bin/ruby", "-I", "/usr/local/lib/ruby/2.6.0", "-r", "./siteconf20191128-258-wzn06g.rb", "extconf.rb"]
checking for geos-config... yes
Using GEOS compile configuration from /usr/bin/geos-config
checking for geos_c.h... yes
checking for GEOSSetSRID_r() in geos_c.h... no
checking for GEOSPreparedContains_r() in geos_c.h... no
checking for GEOSPreparedDisjoint_r() in geos_c.h... no
checking for GEOSUnaryUnion_r() in geos_c.h... no
checking for rb_memhash() in ruby.h... yes
**** WARNING: Unable to find GEOS headers or libraries.
**** Ensure that 'geos-config' is in your PATH or provide that full path via --with-geos-config
**** Compiling without GEOS support.
current directory: /usr/local/bundle/gems/rgeo-2.1.1/ext/geos_c_impl
"make \"DESTDIR=\" clean"
make: *** No rule to make target 'clean'.  Stop.
current directory: /usr/local/bundle/gems/rgeo-2.1.1/ext/geos_c_impl
"make \"DESTDIR=\""
make: Nothing to be done for 'install'.
current directory: /usr/local/bundle/gems/rgeo-2.1.1/ext/geos_c_impl
"make \"DESTDIR=\" install"
make: Nothing to be done for 'install'.
current directory: /usr/local/bundle/gems/rgeo-2.1.1/ext/geos_c_impl
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r ./siteconf20191128-258-wzn06g.rb extconf.rb
current directory: /usr/local/bundle/gems/rgeo-2.1.1/ext/geos_c_impl
make "DESTDIR=" clean
Building has failed. See above output for more information on the failure.
current directory: /usr/local/bundle/gems/rgeo-2.1.1/ext/geos_c_impl
make "DESTDIR="
current directory: /usr/local/bundle/gems/rgeo-2.1.1/ext/geos_c_impl
make "DESTDIR=" install
Successfully installed rgeo-2.1.1
1 gem installed`

Note that we have the same setup and changed nothing to our DockerFile and our production version runs fine on :
- geos 3.7.2-r0
- gdal-2.4.0-r4
- ruby 2.6.0 and Rails 5.2

I also tried the following :
- Upgrade ruby version to 2.6.5
- Also installing ruby-geos package from the alpine edge repo

All geos/gdal files are here, I can see them in my /usr/lib.
I'm really stuck. 😄 

And when I use the "RGeo::Geos.supported?", it still prompts false.

I tried looking for the former versions of the geos/gdal package for alpine edge, but no luck I can't seem to find it !

Setup :
Docker with ruby2.6.0-alpine image
Ruby 2.6.0
Rails 5.2
geos / geos-dev 3.8.0-r0
gdal / gdal-dev 2.4.2-r1

If you ever have some leads on wether it is a compatibility issue or if there are additional steps I could try, I'd be very thankful !

**Comment by watsonjon** [comment]
We are also seeing similar issues. Here are the relevant lines from `mkmf.log`:

```
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libgeos-3.7.2.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libgeos-3.7.2.so: undefined reference to `std::runtime_error::runtime_error(std::runtime_error&&)'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libgeos_c.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
```

Some searching indicates there are libraries compiled with different versions of GCC: https://gcc.gnu.org/onlinedocs/gcc-5.2.0/libstdc++/manual/manual/using_dual_abi.html (see the "Troubleshooting" section).

Hope that helps - we still have not been able to upgrade due to these issues.

**Comment by Kdoggett887** [comment]
After a bit of digging, I was able to get Geos to link with RGeo on a `ruby:2.6.0-alpine` image.

It has something to do with the way `apk` builds `geos` because I was able to upgrade on Ubuntu with no issues, but I got the same error message you did when using `apk`. 

I found [this](https://github.com/OSGeo/gdal/blob/master/gdal/docker/alpine-normal/Dockerfile#L53) and modified the install a little bit, but after doing that I was able to build the extension successfully and `RGeo::Geos.supported?` returned true.

Here's the install:
```
ARG GEOS_VERSION=3.8.0
RUN if test "${GEOS_VERSION}" != ""; then ( \
    wget -q http://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2 \
    && tar xjf geos-${GEOS_VERSION}.tar.bz2  \
    && rm -f geos-${GEOS_VERSION}.tar.bz2 \
    && cd geos-${GEOS_VERSION} \
    && ./configure --prefix=/usr --disable-static \
    && make -j$(nproc) \
    && make install \
    && cd .. \    
    && rm -rf geos-${GEOS_VERSION} \
    ); fi
```

Let me know if this works for you too.

**Comment by watsonjon** [comment]
Our problem ended up being due to differences in gcc versions between images. We use multistage builds and we had to force a rebuild of all our base images to be up to date with the latest geos one from alpine and then it all worked fine. It wasn’t easy to detect as we thought they had all been rebuilt, but you know how that goes. 😪

**Comment by D0ud0v** [comment]
Thanks @Kdoggett887, I ended up rebuilding on a debian image (ruby slim) which makes my docker image bigger, but at least it works !

I'll try to get it working later with the Dockerfile you sent from gdal and I'll let you know if it worked for us !

**Comment by keithdoggett** [comment]
I'm going to close this but if there are still issues, feel free to re-open
