### ISSUE TITLE
New Maintainer Needed

### ISSUE THREAD

**Issue by teeparham** [rgeo/rgeo#216]
Hello!

After over five years of maintaining the RGeo organization and gems, the time has come for me to step down. I can no longer give these projects the attention they deserve, so someone else should take over.

Please submit nominations or volunteer yourself here. I'll let that person take over the organization, and they can add individual contributors to projects (rgeo, activerecord-postgis-adapter, etc.).

Thanks to @dazuma for turning over the reins to me in May 2014 (!). And thanks to the dozens of contributors on all these projects. Viva RGeo!

🌐 🚀 🔢

**Comment by Kdoggett887** [comment]
Hi,

I'm interested in maintaining RGeo or at least being pretty involved going forward. I've been using the gems for about a year and a half now and have explored the codebase to try to understand how it all fits together. 

I understand if you're looking for someone with more experience maintaining OSS, working with GIS, etc., so no hard feelings if it's not the right fit.

Thanks for all the work on this!

**Comment by oyeanuj** [comment]
@keithdoggett @teeparham  Curious if you got maintenance privileges on this gem?

**Comment by keithdoggett** [comment]
@oyeanuj No, I have not.

**Comment by mjy** [comment]
Are we at the point were an "official" fork is necessary?  @teeparham is for all intents and purposes dead here (my apologies if he is in fact so).  Yes there will be issues with leveling-up to reach the level of expertise that developed out this gem, but at this point our group at least is willing to run with that pain rather than not.

**Comment by dazuma** [comment]
Hi, Daniel (the original developer here). Sorry, I hadn't noticed that the maintainership hadn't gotten resolved yet. @teeparham if you are still here, I would prefer if you made the decision on new maintainer(s), since you've been working with the community here more recently than I have. However, if not, I still have admin permissions on the gems and github repos, and I should be able to assign a new maintainer myself if needed.

@keithdoggett if you are still interested, please let us know here. I was also thinking it would be a good idea to have a small team of 2-3 involved just to spread the work out a bit, so anyone else interested in co-maintaining, please also post here. (I'm currently not working with the library in my day job, so I probably should not be part of the team myself.) Either way, if we have at least one volunteer, we'll make a decision and hand over the keys by Aug 14. Thanks everyone! Sorry this has dragged on.

**Comment by keithdoggett** [comment]
Hi, @dazuma thanks for responding to this. Yes, I'm still interested in co-maintaining the project! I definitely think it would be a good idea to have a few maintainers.

If there's anything I can do to help with the process let me know.

**Comment by teeparham** [comment]
@keithdoggett Thanks for stepping up and volunteering. I'll add you as an owner and adding you to rubygems too.

Thanks for the patience, everyone.

**Comment by dazuma** [comment]
Thanks @teeparham !

**Comment by keithdoggett** [comment]
Thanks @teeparham ! Were you able to add my account on rubygems?

**Comment by sergiopantoja** [comment]
@dazuma @teeparham @keithdoggett I'd love to volunteer on this team, in support of @keithdoggett as the new lead. I've been in professional software development for 14 years, professional Ruby development for 6 years. I can immediately help with anything involving the ActiveRecord adapters.

Beyond that, I'm very interested in cultivating the community of Ruby-based GIS software developers. I live in St. Louis, and this city is becoming a geospatial tech hub. The National Geospatial-Intelligence Agency is building its new headquarters here [1][2], and they're pushing hard to scale up local geospatial talent with workshops and hackathons [3].

So outside of helping maintain the library, I'll be showcasing `rgeo` in community events and various demo applications throughout the next few years. Very excited for the future of GIS here and want to make sure Ruby's geospace ecosystem stays strong.

[1] https://gisuser.com/2019/12/vision-for-st-louis-geospatial-intelligence-hub-advanced-with-nga-groundbreaking/
[2] https://www.planetizen.com/news/2020/06/109702-st-louis-plans-become-global-hub-geospatial-tech
[3] https://1904labs.com/our-culture/events/open-source-geospatial-hackathon/

**Comment by keithdoggett** [comment]
Hey @sergiopantoja thanks for volunteering and sharing that info! I'll add you as a maintainer now.

**Comment by ccyrille** [comment]
Hi @dazuma @teeparham @keithdoggett @sergiopantoja, I am the CTO of @klaxit, a company doing daily carpooling in France. We have been developing [geography-related technologies](https://github.com/klaxit/fast-polylines) in Ruby [for some years now](https://github.com/klaxit/loc) with a team of 6 engineers. One of my colleagues, @Quiwin, has already pushed two PR that seem relevant to us (https://github.com/rgeo/rgeo/pull/224 and https://github.com/rgeo/rgeo-geojson/pull/46). We are willing put a significant amount of work on this project in the future, helping on both the issues and future developments. Appart from bringing back to the OSS community, Klaxit is interested in officialy supporting one particular project. Rgeo seems a good candidate to us. What do you think ?

**Comment by keithdoggett** [comment]
Hi, @ccyrille thanks for volunteering to support RGeo and for the contributions your team has already pushed. That would be great if the @klaxit team would be willing to help support the project and I am totally for it.

I think from a management perspective, the best option is for your team to nominate one member to be the representative and I can make them a maintainer. They'd be responsible for the planning and other discussions about the direction of the project. Of course contributions would still be welcome from your entire team.

Let me know your thoughts!

**Comment by ccyrille** [comment]
Hi @keithdoggett, thanks for having thought about it. I am pleased that you welcome our proposal. We have discussed internally and @BuonOmo seems the perfect fit to take the lead on @klaxit's side ! Thanks in advance for adding him to the maintainers.

**Comment by keithdoggett** [comment]
Thank you @ccyrille I've just invited @BuonOmo to the team. Looking forward to working with your team!

**Comment by BuonOmo** [comment]
Hi @keithdoggett and all the RGeo Team!

Thank you very much for the invitation 🙂

I think the best way to introduce myself for those who are wondering is through https://github.com/klaxit/fast-polylines, on which I improved performances by a 30x factor with a c rewrite.

Anyway, I have already take a deep look at `RGeo` and `RGeo::GeoJOSN`'s codebases. And of course, I already reviewed my peer's pull requests (https://github.com/rgeo/rgeo-geojson/pull/46, #224), which I could approve really soon, after I know a bit more about your review process.

I'd be glad to know about your review process and issue prioritising. If there is a mailing list I should join, or if we could exchange further about working together without filling this thread, my email address is firstname.lastname [at] klaxit.com.

Looking forward to collaborate on this great gem!

**Comment by akshitagupta15june** [comment]
Request for joining the organizatio

**Comment by BuonOmo** [comment]
Hi @akshitagupta15june,

It is true we are still looking for one more potential maintainer. But for now what is most important is having more contributors. I'll add issues marked as `good first issue` such as #231 on which you're invited to contribute!

If you still want to join the organisation as a maintainer, you would need to provide more background information, _why_ you want to participate and how you can help us.

Thanks for requesting anyway, I hope we'll see you in our git log soon !

**Comment by rywall** [comment]
Hi @BuonOmo,

I've contributed [several PRs](https://github.com/rgeo/rgeo-shapefile/pulls/rywall) to `rgeo-shapefile`. I use this gem in a couple of my projects. Most of my experience is with this gem specifically and not the other gems under the `rgeo` umbrella. I'm fine to just keep contributing PRs but would also be happy to help reviewing and merging PRs on the `rgeo-shapefile` gem if you'd like some help.

Cheers,
Ryan

**Comment by BuonOmo** [comment]
Hi @rywall,

Thank you very much for offering your help! Right now we are two maintainers (@keithdoggett and I) and need to be a bit more (we are targeting a team of 3 or 4). Moreover, we're thinking about handing specific projects to specific maintainers to reduces the scope of our work. Hence your offer seems right in the spot!

I'm in. I'll let @keithdoggett decide whether it is ok for him as well 🙂

Ulysse

**Comment by keithdoggett** [comment]
@rywall thanks for reaching out! To echo @BuonOmo I think it would be great to have you as a maintainer on `rgeo-shapefile`, especially since you've already made PRs for it. Looking forward to working together.

**Comment by rodrei** [comment]
Hello! 👋 

As a new potential user of the ActiveRecord adapter I was wondering if someone could give a status update on the project? Are you still looking for maintainers? 

Specially If we decide to use this we'd definitely like to get involved and help in any way we can.

Thanks!

**Comment by BuonOmo** [comment]
Hi @rodrei,

We are nowadays two maintainers (@keithdoggett and I). We are able to answer most questions in a reasonable delay I think. However, this issue is open because we'd rather be a little more (we are not always available), or at least have active core contributors we could easily rely on.

If you want to get involved, I'd be glad to meet and discuss further how we could manage that, would that be ok? And you can already start contributing on the open issues. In the meantime we'll be discussing what we could do with Keith.

Thanks for reaching out 🙂

**Comment by rodrei** [comment]
hi @BuonOmo! Sorry for the late response, I thought I had replied but didn't 🙈.

Thanks for the update on the status of the project. There's a high chance we'll start using the AR adapter within the next few weeks, if that happens I'll be happy to get involved and help in any way I can. I'm an experienced Ruby and Rails dev, but quite new to Postgis and Gis in general.

**Comment by keithdoggett** [comment]
Hi @rodrei thank you for taking interest in the project and offering your support. Since you said you're not as familiar with GIS but know Rails and AR, I think some help on this PR would be a great place to start (https://github.com/rgeo/activerecord-postgis-adapter/pull/363).

The goal is to test against our specific PostGIS tests as well as the full ActiveRecord test suite so we can be sure that we're fully compatible or at least aware of areas where we're missing compatibility. I've done a fair amount of work on it and I believe the PR is almost there, but there's an issue where our PostGIS tests will fail when running the entire AR suite as well.

I think this PR would be a good place to start since it doesn't require any GIS knowledge and would be a good way to familiarize yourself with the codebase. @BuonOmo and myself would of course help out along the way and offer any guidance necessary. Happy to discuss more in detail once you start using the library!

**Comment by rodrei** [comment]
Thanks @keithdoggett, sounds like a good plan!

**Comment by Jay-Dabo** [comment]
@keithdoggett I am interested in working on this project as well

**Comment by BuonOmo** [comment]
@Jay-Dabo thanks for your interest. The best proof of motivation we could get is you tackling an open issue! Of course we'll help you get into it, and we can choose the topic together.

It would also be nice that you tell a bit more about you: how do you intend to contribute ? And why do you want to ?

Anyway, thanks again. I hope we can soon be working together 😄

**Comment by teeparham** [comment]
I'm closing this ticket. Thanks to @keithdoggett and @BuonOmo  and others who have taken over.

**Comment by dazuma** [comment]
Thanks @teeparham for all the years you served as maintainer! The project couldn't have continued strong without you!

**Comment by BuonOmo** [comment]
Ok we'll open a new one then I think, as a new maintainer would help us a lot!

**Comment by andresgutgon** [comment]
Hey, first of all thanks a lot for this software. I didn't even started using it and I'm already appreciate it <3 
Regarding project status I see in the README that is still the notice about maintainers. So I'm curios to know if the project already has maintainer and in that case if we can remove the warning from README

**Comment by keithdoggett** [comment]
Hey @andresgutgon yes it is actively maintained by myself and @BuonOmo. We are still looking for additional contributors as both of us have been very busy recently and haven't had as much time to put towards development on RGeo.

I can unpin this, remove the warning and change it to a note about contributors.

**Comment by andresgutgon** [comment]
Awesome @keithdoggett thanks!

**Comment by BuonOmo** [comment]
Definitely, thanks for your attention @andresgutgon. We're also looking for active users, to get feedback. So if you are using RGeo often don't hesitate to ping us by opening an issue :)

**Comment by andresgutgon** [comment]
So f AR I just tried it with rails and it works great. I just tried only with rspec tests not in production though. But the gem has a great API!
