### ISSUE TITLE
Parse error, multi_polygon, Z-coordinate included

### ISSUE THREAD

**Issue by dsshap** [rgeo/rgeo#223]
Hello, I have imported records into Postgres with the below insert statement. The records were accepted. When I query the data using the ActiveRecord extension I get the following error.

I suspect this is because the multi_polygon includes a z coordinate that is not getting parsed accordingly.

I am a bit lost about where this change needs to happen to account for the three coordinates. Can someone point me in the appropriate direction?

Error:
```
RGeo::Error::InvalidGeometry: Parse error
from /Users/dsshap/.rvm/gems/ruby-2.6.3@projabc/gems/rgeo-2.1.1/lib/rgeo/geos/capi_factory.rb:372:in `multi_polygon'
```

Insert SQL example
```
INSERT INTO buildings (geom, object_id, object_bin) VALUES ('SRID=2263; MULTIPOLYGON(((992797.580333918 216792.153735816 42.0951999999961,992739.212012336 216686.603750065 42.0951999999961,992704.904010072 216705.575496897 42.0951999999961,992763.27233167 216811.125482649 42.0951999999961,992797.580333918 216792.153735816 42.0951999999961)))'::geometry, '1234', '5678');
```

DB Schema
```
ActiveRecord::Schema.define(version: 2020_09_30_214837) do
  enable_extension "plpgsql"
  enable_extension "postgis"

  create_table "buildings", force: :cascade do |t|
    t.string "object_id"
    t.string "object_bin"
    t.geometry "geom", limit: {:srid=>2263, :type=>"multi_polygon", :has_z=>true}
    t.index ["geom"], name: "index_buildings_on_geom", using: :gist
    t.index ["object_bin"], name: "index_buildings_on_object_bin"
  end
end
```

**Comment by keithdoggett** [comment]
This is probably because the factory that is being used to parse the geometry from the database does not support z coordinates. You specify specific factories to use based on `srid`, `has_z` and other parameters by registering them with the `SpatialFactoryStore`. More info on how to do this can be found here https://github.com/rgeo/rgeo-activerecord#spatial-factories-for-columns.

Note that sometimes you have to be very specific with the parameters to register them for a specific column, which is a bug I'm looking into. For example, you may have to specify your factory like this

```ruby
RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
  config.default = RGeo::Geographic.simple_mercator_factory.projection_factory

  config.register(RGeo::Geographic.spherical_factory(srid: 4326), srid: 4326, geo_type: 'Point',
                                                                  has_m: false, has_z: false,
                                                                  sql_type: 'geography(Point,4326)')
end
```

rather than

```ruby
config.register(RGeo::Geographic.spherical_factory(srid: 4326), srid: 4326, geo_type: 'point'))
```

**Comment by dsshap** [comment]
Thank you for the prompt response.

I took your advice but its still having problems parsing the data.

Factory setup
```
RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
  config.default = RGeo::Geographic.spherical_factory.projection_factory

  config.register(RGeo::Geographic.spherical_factory(srid: 2263), srid: 2263, geo_type: 'MultiPolygon',
                                                                  has_m: false, has_z: true, sql_type: 'geography(MultiPolygonZ,2263)')
end
```

Schema Dump
```
CREATE TABLE public.buildings (
    id bigint NOT NULL,
    object_id character varying,
    object_bin character varying,
    geom public.geometry(MultiPolygonZ,2263)
);
```

**Comment by keithdoggett** [comment]
There are 2 issues I see with your setup.

1) The `register` method takes the desired factory as the first parameter and the descriptors as kwargs. For your instance, you need to configure your factory differently so that it accepts z coordinates.

For example:

```rb 
RGeo::Geos.factory(has_z_coordinate: true, srid: 2263)
```

so the config should be 

```rb
config.register(RGeo::Geos.factory(has_z_coordinate: true, srid: 2263), srid: 2263, geo_type: 'MultiPolygon',
                                                                  has_m: false, has_z: true, 
                                                                  sql_type: 'geography(MultiPolygonZ,2263))
```

2) You used `RGeo::Geographic.spherical_factory`, which I had in my example, but that is likely not the factory type that you want since that assumes you're working with latitudes and longitudes. You probably want to do something like I did above that uses a geometric factory as opposed to a geographic factory.

Also as a note, if this is the only column that you're using geometries with, you can just use the `config.default` option in the setup so that you don't have to match the column exactly with the kwargs in the `register` method.

**Comment by keithdoggett** [comment]
I took another look at this and I was able to get this example to work using the following initializer:

```rb
#config/initializers/rgeo_factory.rb
RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
  config.default = RGeo::Geographic.spherical_factory(srid: 4326)


  config.register(RGeo::Geos.factory(has_z_coordinate: true, srid: 2263), srid: 2263, geo_type: 'MultiPolygon',
                                                                          has_m: false, has_z: true,
                                                                          sql_type: 'geometry(MultiPolygonZ,2263)')
end

```

output:
```
Building.first
  Building Load (7.2ms)  SELECT "buildings".* FROM "buildings" ORDER BY "buildings"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => #<Building id: 2, geom: #<RGeo::Geos::CAPIMultiPolygonImpl:0x3fe640257b6c "MULTIPOLYGON (((992797.580333918 216792.153735816 42.0951999999961, 992739.212012336 216686.603750065 42.0951999999961, 992704.904010072 216705.575496897 42.0951999999961, 992763.27233167 216811.125482649 42.0951999999961, 992797.580333918 216792.153735816 42.0951999999961)))">, created_at: "2020-10-08 21:41:44", updated_at: "2020-10-08 21:41:44"> 
```

The default factory is spherical, but for this column we use a CAPI geos factory.

I also think you're using an outdated `activerecord-postgis-adapter` version because the adapter is supposed to return `nil` on a parse error instead of throwing it like yours did.

I'm going to close this since it doesn't seem like an issue, but if you try my solution above and it still fails feel free to re-open or continue in the comments and I can try to help.
