### ISSUE TITLE
Support contains? for SphericalPolygon

### ISSUE THREAD

**Issue by x4d3** [rgeo/rgeo#226]
Issue similar to https://github.com/rgeo/rgeo/issues/142

When using `contains?` on a SphericalPolygon I get this error:
```
RGeo::Error::UnsupportedOperation: Method Geometry#contains? not defined.
```

It would be awesome to implement it for these polygons as well.

**Comment by BuonOmo** [comment]
This might be fixed by #224. We'll take a look at it after having merged the Pull Request.

**Comment by x4d3** [comment]
@BuonOmo exactly. Thanks for looking into it !

**Comment by BuonOmo** [comment]
@x4d3 thanks for opening.

We've discussed it a bit, and in fact the implementation cannot be the same, I misunderstood the fact that the Spherical factory is based on arcs, whereas the implementation made in #224 is based on segments (line-strings). Hence this should differ a bit. Bit I guess by reading #142 and #224 it should be pretty straight-forward to implement. @x4d3 would you like to try that ?

Otherwise we'll treat it, but later, since there are higher priority issues we need to handle yet!

**Comment by x4d3** [comment]
Thanks @BuonOmo 
I'll try to have a look, but I'm not sure I'll be able to fully understood the implication of the implementation, and maybe I was a bit naive thinking it could be easily implemented.

**Comment by keithdoggett** [comment]
A basic version of `contains?` is implemented in version 3 that handles points for all factories.
