### ISSUE TITLE
Set Precision for Coordinates

### ISSUE THREAD

**Issue by preisb** [rgeo/rgeo#285]
As mentioned in https://github.com/rgeo/rgeo-geojson/issues/23 there would be a way to reduce the precision of coordinates for output e.g. as geojson. Is this somewhere on the roadmap?

If not, I could try to add a PR - if it is desired. If this is the case, I would ask you for some hints, how this would be implemented.

**Comment by keithdoggett** [comment]
Hi @preisb we don't currently have that on the roadmap,  but if you're interested in tackling it we'd greatly appreciate it and will help out along the way.

I think it would make sense to model it off of how JTS/GEOS handles it because that way it would be easy to enable precision in GEOS factories as well as cartesian/spherical factories. GEOS uses a precision model object as a parameter in their factories. I'm not sure exactly how it works, but I assume that every point created in that factory with a precision model will be bound to that grid. Here are the JTS docs on it: https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/PrecisionModel.html.

In addition to that, it could be nice to map existing geometries to a specific precision, so adding a `to_precision(scale)` method would be nice as well, but this will be dependent on how we implement the first part I think.

So to start we should figure out how the precision model works in JTS and see how that maps over to RGeo from a high level, then we can get into the specifics of what would need to be done for each factory type.

**Comment by preisb** [comment]
@keithdoggett thanks for the directions. I will look into it.

**Comment by keithdoggett** [comment]
Thanks @preisb! If you have any questions along the way or something you want to discuss please post it in here and we can work through it.

**Comment by preisb** [comment]
@keithdoggett I wanted to inform you, that we have stopped development on this feature. It turned out that for our usecase [ST_AsGeoJSON](https://postgis.net/docs/ST_AsGeoJSON.html) with the `maxdecimaldigits` argument suites best.
Thanks for your help.
