### ISSUE TITLE
intersection, intersects, within don´t work

### ISSUE THREAD

**Issue by laromicas** [rgeo/rgeo#34]
i find the within command not working, and found than even in the simpler examples like the first one in 
http://www.daniel-azuma.com/blog/archives/28 don´t work.

line3 = polygon.intersection(line2)

throws the error

RGeo::Error::UnsupportedOperation: Method Geometry#intersection not defined.
        from lib/ruby/gems/1.9.1/gems/rgeo-0.3.14/lib/rgeo/feature/geometry.rb:532:in `intersection'
        from (irb):19
        from bin/irb:12:in`<main>'

**Comment by HenrYxZ** [comment]
I'm using Linux, I installed libgeos-dev and have libgeos-3.4.2 packages.
I reinstalled rgeo, rgeo-activerecord and activerecord-postgis-adapter gems by running `gem uninstall [gem_name]` in the Rails app directory and then run `bundle install`.
But still when I run

 ```ruby
RGeo::Geos.supported?
``` 

I get false and intersection is not working. Do you know how to solve this?

**Comment by HenrYxZ** [comment]
Ok, I made it work. I uninstalled rgeo again, installed libproj-dev, and run

    /usr/lib$ sudo ln -s libgeos-3.4.2.so libgeos.so

It didn't work. Then I cloned the rails project in another directory and bundle install there.
It gave an error message saying that it couldn't install pg gem. I was only using that gem because I'm using a remote psql database but sqlite local db. Then I installed libpq-dev package, bundle install and it worked in both the directory and the old directory.
