### ISSUE TITLE
`test_invalid_polygon_duplicate_rings` test is failing

### ISSUE THREAD

**Issue by haroon26** [rgeo/rgeo#348]
Hello! I have been working on a reported issue of `rgeo`. After my implementation, I ran all the test cases, but 3 test cases were failed. To be sure if these failures are due to my changes, I again ran test cases on `main` branch. But those test cases are failing there too.  The failed test cases are follwowing:
```
1) Failure:
MercatorValidityTest#test_invalid_polygon_duplicate_rings [/home/haroon/Project/opensource/rgeo/test/common/validity_tests.rb:227]:
Expected: "Self-intersection"
  Actual: "Duplicate Rings"

  2) Failure:
GeosFFIValidityTest#test_invalid_polygon_duplicate_rings [/home/haroon/Project/opensource/rgeo/test/common/validity_tests.rb:227]:
Expected: "Self-intersection"
  Actual: "Duplicate Rings"

  3) Failure:
GeosValidityTest#test_invalid_polygon_duplicate_rings [/home/haroon/Project/opensource/rgeo/test/common/validity_tests.rb:227]:
Expected: "Self-intersection"
  Actual: "Duplicate Rings"
```

### Steps to reproduce
`bundle exec rake`

### Expected behavior
All test cases should pass.

### Actual behavior
3 test cases are failing.

### System configuration

**Ruby version**:
`2.7.1`

**OS**:
Ubuntu 20.04.5 LTS

**Comment by keithdoggett** [comment]
Hey @haroon26 what version of Geos are you using? A version was recently released where they changed the priority of validity checks, so if you're using an older version it might be doing duplicate ring checks first.

**Comment by keithdoggett** [comment]
Ok then that is expected. I think the update happened in either Geos version 3.10 or 3.11. On ubuntu you can do the following to get newer versions

```sh
sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get install -yqq libgeos-dev
```

which is what we do in our CI.

One of the things I want to work on soon is add all supported versions of Geos to the CI and once that happens, we can figure out how to handle it in the tests.

I'm going to close since this behavior is expected from older versions of Geos, but I can open a new issue about expanding the CI. Let me know if you have any more questions about it.
